#lang racket
(require csv-reading)
(require racket/dict)
(require csv-writing)

(define (read-csv file)
    (csv->list (make-csv-reader (open-input-file file)))
)  

(define data (read-csv "data.csv"))
(display 'data: )
(display data)
(newline)
(display 'Columns: )
(display (caar data))
(define cols (caar data))
(newline)
(display 'Rows: )
(display (cadar data))
(define rows (cadar data))
(newline)

(define (cell-to-dict cell)
    (map (lambda (x) (string-split x ".")) (string-split cell ";")))
    

(define (rows-to-cells rows)
    (map (lambda (row) (map cell-to-dict row)) rows))

(define (create-dict data-input [dict (make-hash)] [n 1])
    (define (create-dict-helper data-input-fun dict n)
        (if (null? data-input-fun)
            dict 
            (create-dict-helper (cdr data-input-fun) (dict-set dict n (car data-input-fun)) (+ n 1))))
    (create-dict-helper data-input dict n))

;Remove product -> name quantity
(define (get-new-removed-list name quantity lista)
    (if (null? lista)
        (raise "product not found")
        (begin
            (newline)
            (display 'In-Get-New-Removed-Lista: )
            (display lista)
            (newline)
            (display 'name: )
            (display name)
            (newline)
            (display (caar lista))
            (if (string-ci=? (car (car lista)) name)
            (if (>= (string->number (cadr (car lista))) quantity)
                (cons (list name (- (string->number (cadr (car lista))) quantity) (caddr (car lista))) (cdr lista))
                (raise "not enough quantity"))
            (cons (car lista) (get-new-removed-list name quantity (cdr lista)))))
    )
)
(define (remove-product name quantity state-dict)
    (begin
        (newline)
        ; (display 'In-Remove: )
        ; (display state-dict)
        ; (newline)
        (display 'name: )
        (display name)
        (newline)
        (display 'quantity: )
        (display quantity)
        (newline)
        (display "[DEBUG]")
        (newline)
        (newline)
        (display (car state-dict))
        (newline)
        (newline)
        (display (cadr state-dict))
        (newline)
        (list (dict-set (car state-dict) (cadr state-dict) (get-new-removed-list name quantity (dict-ref (car state-dict) (cadr state-dict)))) (cadr state-dict)))
)

;Add product -> name quantity
(define (get-new-added-list name quantity lista)
    (if (null? lista)
        (raise "product not found")
        (begin
            (newline)
            (display 'In-Get-New-Added-Lista: )
            (display lista)
            (newline)
            (display 'name: )
            (display name)
            (newline)
            (display (caar lista))
            (if (string-ci=? (car (car lista)) name)
            (cons (list name (+ (string->number (cadr (car lista))) quantity) (caddr (car lista))) (cdr lista))
            (cons (car lista) (get-new-added-list name quantity (cdr lista)))))
    )
)

(define (add-product name quantity state-dict)
    (begin
        (newline)
        ; (display 'In-Add: )
        ; (display state-dict)
        ; (newline)
        (display 'name: )
        (display name)
        (newline)
        (display 'quantity: )
        (display quantity)
        (newline)
        (display "[DEBUG]")
        (newline)
        (newline)
        (display (car state-dict))
        (newline)
        (newline)
        (display (cadr state-dict))
        (newline)
        (list (dict-set (car state-dict) (cadr state-dict) (get-new-added-list name quantity (dict-ref (car state-dict) (cadr state-dict)))) (cadr state-dict)))
)

;Add product -> name quantity
; (define (get-new-added-list name quantity lista)
;     (if (null? lista)
;         (cons (list name quantity) lista)
;         (if (string-ci=? (car (car list)) name)
;             (cons (list name (+ (cadr (car list)) quantity)) (cdr list))
;             (cons (car list) (get-new-added-list name quantity (cdr list))))
;     )
; )

; (define (add-product name quantity state-dict)
;     '((dict-set (car state-dict) (cdar state-dict) (get-new-added-list name quantity (dict-ref (car state-dict) (cdar state-dict)))) (cdr state-dict))
; )

;Move state
(define (move-direction dir state-dict)
    (cond 
        ((equal? dir 'up)
            (if (<= (cadr state-dict) (string->number cols))
                (list (car state-dict) (- (string->number rows) (string->number cols)))
                (list (car state-dict) (- (cadr state-dict) (string->number cols)))))
        ((equal? dir 'down)
                (if (> (cadr state-dict) (* (string->number rows) (- (string->number cols) 1)))
                (list (car state-dict) (+ (cadr state-dict) (- (string->number cols) (* (string->number rows) (- (string->number cols) 1)))) )
                (list (car state-dict) (+ (cadr state-dict) (string->number cols))))
        )
        ((equal? dir 'left)
            (if (equal? (modulo (cadr state-dict) (string->number cols)) 0)
                (list (car state-dict) ((string->number cols)))
                (list (car state-dict) (- (cadr state-dict) 1))))
        ((equal? dir 'right)
            (if (equal? (modulo (cadr state-dict) (string->number cols)) (- (string->number cols) 1))
                (list (car state-dict) (- (cadr state-dict) (- (string->number cols) 1)))
                (list (car state-dict) (+ (cadr state-dict) 1))))
        (else (raise "invalid direction"))
    )
)

;Show current cell
(define (show-cell state-dict)
    (begin 
        (display (dict-ref (car state-dict) (cadr state-dict)))
        (newline)
        state-dict)
)
(define simplyfy-list (lambda (list) (apply append list)))
(define dict (create-dict (simplyfy-list (rows-to-cells (cdr data))) (hash) 1))
(define state-dict-objct (list dict 1))
(define instuctions-query '((show) (move down) (show) (remove "JetsonNano" 2) (show) (move right) (show) (move up) (show) (add "Serrucho" 5) (show)))

(define (execute-query-helper state-dict query)
    (cond
        ((equal? (car query) 'show)
            (show-cell state-dict)
            )
        ((equal? (car query) 'move)
            (begin
                (display 'Move:)
                (display (cadr query))
                (move-direction (cadr query) state-dict)))
        ((equal? (car query) 'remove)
            (begin
                (newline)
                (display 'Remove:)
                (display (cadr query))
                (display (caddr query))
                (newline)
            (remove-product (cadr query) (caddr query) state-dict)))
        ((equal? (car query) 'add)
            (add-product (cadr query) (caddr query) state-dict))
        (else (raise "invalid query")))
)

(define (execute-query state-dict query)
    (begin
    (newline)
    (display 'query: )
    (display query)
    (newline)
    (if (null? query)
        state-dict
        (begin 
        ; (newline)
        ; (display 'state-dict: )
        ; (display state-dict)
        ; (newline)
        (newline)
        (execute-query (execute-query-helper state-dict (car query)) (cdr query)))
        ))
)

(define (to-full-string-list lista)
    (if (null? lista)
        '()
        (if (string? (car lista))
            (cons (car lista) (to-full-string-list (cdr lista)))
            (cons (number->string (car lista)) (to-full-string-list (cdr lista))
            ))
    )
)

(define list-to-string (lambda (lista) (string-join (to-full-string-list lista) ".")))


(define (to-string lista)
    (if (null? lista)
        ""
        (if (null? (cdr lista))
            (list-to-string (car lista))
            (string-append (list-to-string (car lista)) ";" (to-string (cdr lista))))
    )
)

(define (to-list graph n)
    (if (equal? (modulo n (string->number cols)) 0)
        (string-append (to-string (dict-ref graph n)) "\n")
        (cons (to-string (dict-ref graph n)) (to-list graph (+ n 1))))
)





(newline)
(newline)
(to-string (dict-ref (car state-dict-objct) 1))
(newline)
(define (to-row graph n)
    (if (equal? (modulo n (string->number cols)) 0)
        (list (to-string (dict-ref graph n)))
        (cons (to-string (dict-ref graph n)) (to-row graph (+ n 1))))
)

(define (to-matrix graph n)
    ; from 1 to 1 + cols... to row*(cols - 1)
    (if (> n (+ 1 (* (string->number rows) (- (string->number cols) 1))))
        '()
        (cons (to-row graph n) (to-matrix graph (+ n (string->number cols))))
    )
)

; de https://stackoverflow.com/questions/61023450/scheme-how-to-write-list-of-lists-into-csv-file
(define (write-to-a-file lst path)
  (call-with-output-file path
    (lambda (output-port)
      (display-table lst output-port))
    #:exists 'replace))


(to-matrix (car state-dict-objct) 1)

(define changed-graph (execute-query state-dict-objct instuctions-query))

(write-to-a-file (cons (list rows cols) (to-matrix (car changed-graph) 1)) "output.csv")